### ISSUE TITLE
more than one renderer create leveldb error

### ISSUE THREAD

**Issue by milu2003** [cosmosgenius/electron-leveldb#1]
Hello, I recently used leveldb in electron.

I saw you were  create leveldb in renderer.

If more than one renderer this will be a problem。

Do you have any solutions？

**Comment by cosmosgenius** [comment]
Two ways to solve this:
- By opening leveldb in the `main` and use ipc to access leveldb in `renderer`.
- Open and close leveldb before and after every operation respectively.

This was a test project to demonstrate https://github.com/electron-userland/electron-builder/issues/647.

Probably I'll update the project to open leveldb in main.

**Comment by milu2003** [comment]
i just try opening in main. But there is a problem

use it in renderer:

```
`var rs = testdb.createReadStream(this.valueOps)

testdb.open();

rs.on('data' , function (data) {
   console.log(data.key, '=', data.value)

})
rs.on('error', function (err) {
    dlog(err);
})
rs.on('close', function () {
    dlog('关闭');
})
rs.on('end', function () {
    dlog('结束');
});
`
```

He did not execute the end callback

see my other issues:
https://github.com/Level/levelup/issues/404

Although I closed the issues, but later found that there will still be a problem

You can test it on your project

**Comment by milu2003** [comment]
I just close and open database when I was created.

> Open and close leveldb before and after every operation respectively.

Maybe in accordance with what you said, each operation is closed open may be able to solve the problem

But is the price too high? Performance is very affected by it?
